"""Project scaffolding + test generation (§15.2, USER_GUIDE §3-5).

`init` lays out a tests folder; `new-test` writes a ready-to-run, mutation-verified
test from a per-control template built on the authoring DSL.
"""
from __future__ import annotations

from pathlib import Path

_REAPROOF_TOML = """\
[plugin]
name      = "{plugin}"
formats   = ["JSFX"]          # VST3 / CLAP / AU / JSFX
targets   = ["macos"]         # windows / macos / linux (CI verifies non-host)

[defaults]
sample_rate = 48000
block_size  = 512
dpi_scales  = [100]
strictness  = 5
"""

_CONFTEST = """\
# pytest wiring for a ReaProof test folder. Don't edit unless you know why.
# Loads the ReaProof plugin (auto-repeat/quarantine, report + provenance, mutation
# tracking) for THIS project only — it never auto-loads into unrelated pytest runs.
pytest_plugins = ["reaproof.runner.pytest_plugin"]
"""

KNOB_TEMPLATE = '''\
# Generated by `reaproof new-test --type knob`.
# A fully mutation-verified knob test: functional/DSP + visual dual-channel.
import pytest
from reaproof.authoring import assert_gain_db, knob_editor

pytestmark = [pytest.mark.reaper, pytest.mark.slow]

FX_DESC = "{fx_desc}"          # the editor window title (JSFX desc)
FX_NAME = "JS: {fx_desc}"      # how TrackFX_AddByName finds it
JSFX    = "{jsfx_pattern}"     # which JSFX file(s) to install
VRANGE  = ({vmin}, {vmax})


def test_{control}_dsp_gain():
    # The knob actually changes the sound: at -6 dB the output RMS is 6 dB below the
    # reference render (asserted on rendered audio; mutation-verified with x0.5).
    assert_gain_db(JSFX, FX_NAME, set_db=-6.0, tol_db=0.1)


def test_{control}_visual_dual_channel():
    # The knob draws correctly: the reported value and the drawn indicator angle agree
    # (mutation-verified — a forced wrong angle turns this RED).
    with knob_editor(FX_DESC, jsfx_pattern=JSFX, vrange=VRANGE, name="{control}") as knob:
        knob.assert_dual_channel(-6.0)
'''


def init_project(path: str | Path) -> Path:
    root = Path(path)
    (root / "tests").mkdir(parents=True, exist_ok=True)
    (root / "goldens").mkdir(exist_ok=True)
    if not (root / "reaproof.toml").exists():
        (root / "reaproof.toml").write_text(_REAPROOF_TOML.format(plugin="MyPlugin"))
    (root / "tests" / "conftest.py").write_text(_CONFTEST)
    return root


def new_test(out_dir: str | Path, *, type: str = "knob", control: str = "GainKnob",
             fx_desc: str = "ReaProof Gain (custom rotary knob)",
             jsfx_pattern: str = "ReaProof_Gain.jsfx",
             vrange=(-24, 24)) -> Path:
    if type != "knob":
        raise NotImplementedError(f"test type '{type}' — knob is implemented; "
                                  "param/dsp/visual/interaction/state share the same DSL")
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    body = KNOB_TEMPLATE.format(control=control.lower(), fx_desc=fx_desc,
                                jsfx_pattern=jsfx_pattern, vmin=vrange[0], vmax=vrange[1])
    dest = out / f"test_{control.lower()}.py"
    dest.write_text(body)
    return dest
